# Generated by Django 5.2.6 on 2025-09-13 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='complaints/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('resolved_image', models.ImageField(blank=True, null=True, upload_to='resolved/')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('mun_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('head_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civicApp.municipality')),
            ],
        ),
    ]
