# Generated by Django 5.2.6 on 2025-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='dept',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='complaints',
            name='worker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='worker_num',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
