# Generated by Django 5.2.6 on 2025-09-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicApp', '0002_complaints_dept_complaints_worker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civicApp.municipality'),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='worker_num',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
