# Generated by Django 5.2.6 on 2025-09-14 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicApp', '0003_complaints_municipality_alter_complaints_worker_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='civicApp.municipality'),
        ),
        migrations.AlterField(
            model_name='department',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civicApp.municipality'),
        ),
    ]
