# Generated by Django 5.2.6 on 2025-09-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civicApp', '0004_alter_complaints_municipality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='dept',
            field=models.CharField(default='General Department', max_length=100),
        ),
    ]
